spring.application.name=SpringCorePractice
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringCoreDB
spring.datasource.username=postgres
spring.datasource.password=Haitac2004
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update